all:
  children:
    spines:
      hosts:
        dc1-spsw1:
          mgmt_ip: 10.0.0.1/24
          vpc_peer: 10.0.0.2
          vpc_prio: 20
        dc1-spsw2:
          mgmt_ip: 10.0.0.2/24
          vpc_peer: 10.0.0.1
          vpc_prio: 30
    leaves:
      hosts:
        dc1-lfsw1:
          mgmt_ip: 10.0.0.11/24
        dc1-lfsw2:
          mgmt_ip: 10.0.0.12/24
  vars:
    dns1: 8.8.8.8
    dns2: 8.8.4.4
    domain: network.example.com
    ntp1: 1.nl.pool.ntp.org
    ntp2: 2.nl.pool.ntp.org
    vpc_domain: 1
    native_vlan: 3999
    infra_vlans:
      - id: 3999
        name: empty_native
    links:
      - connections:
          - name: dc1-spsw1
            intf: Ethernet 2/1
            ch_id: 1
            type: vpc-peer
          - name: dc1-spsw2
            intf: Ethernet 2/1
            ch_id: 1
            type: vpc-peer
      - connections:
          - name: dc1-spsw1
            intf: Ethernet 2/2
            ch_id: 1
            type: vpc-peer
          - name: dc1-spsw2
            intf: Ethernet 2/2
            ch_id: 1
            type: vpc-peer
      - connections:
          - name: dc1-spsw1
            intf: Ethernet 1/1
            ch_id: 11
            type: vpc-downlink
          - name: dc1-lfsw1
            intf: Ethernet 2/1
            ch_id: 1
            type: leaf-uplink
      - connections:
          - name: dc1-spsw2
            intf: Ethernet 1/1
            ch_id: 11
            type: vpc-downlink
          - name: dc1-lfsw1
            intf: Ethernet 2/2
            ch_id: 1
            type: leaf-uplink
      - connections:
          - name: dc1-spsw1
            intf: Ethernet 1/2
            ch_id: 12
            type: vpc-downlink
          - name: dc1-lfsw2
            intf: Ethernet 2/1
            ch_id: 1
            type: leaf-uplink
      - connections:
          - name: dc1-spsw2
            intf: Ethernet 1/2
            ch_id: 12
            type: vpc-downlink
          - name: dc1-lfsw2
            intf: Ethernet 2/2
            ch_id: 1
            type: leaf-uplink
    services:
      - name: service_1
        vlan_id: 10
        interfaces:
          - host: dc1-lfsw1
            intf: Ethernet 1/2
            type: access
            peer_intf: host1_eth1
      - name: service_2
        vlan_id: 20
        interfaces:
          - host: dc1-lfsw1
            intf: Ethernet 1/1
            type: trunk
            peer_intf: host2_eth1
          - host: dc1-lfsw2
            intf: Ethernet 1/1
            type: trunk
            peer_intf: host2_eth2
      - name: service_3
        vlan_id: 30
        interfaces:
          - host: dc1-lfsw1
            intf: Ethernet 1/1
            type: trunk
            peer_intf: host2_eth1
          - host: dc1-lfsw2
            intf: Ethernet 1/1
            type: trunk
            peer_intf: host2_eth2
      - name: service_4
        vlan_id: 40
        interfaces:
          - host: dc1-lfsw1
            intf: Ethernet 1/3
            type: access
            peer_intf: host3_eth1
